name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        env:
          SURGE_SECRET_TOKEN: ${{ secrets.SURGE_SECRET_TOKEN }}
        run: surge ./ https://pagina-electiva2-2025.surge.sh --token $SURGE_SECRET_TOKEN

